"""Canonical Milhouse domain contracts."""

from milhouse.domain.identity import (
    RecordDedupeV1,
    RecordIdentityV1,
    derive_content_hash,
    derive_dedupe_key,
    derive_record_id,
)
from milhouse.domain.records import (
    ActorReferenceV1,
    AlertDataV1,
    AuditDataV1,
    CollectorDescriptorV1,
    CorrelationV1,
    EventDataV1,
    FeedbackItemDataV1,
    FeedbackTransitionDataV1,
    IncidentDataV1,
    MetricDataV1,
    RecordDraftV1,
    RecordEnvelopeV1,
    RecordError,
    RunDataV1,
    SourceDescriptorV1,
    SpanDataV1,
    TargetDescriptorV1,
    VerificationSpecV1,
    finalize_record,
    verify_record_identity,
)

__all__ = [
    "ActorReferenceV1",
    "AlertDataV1",
    "AuditDataV1",
    "CollectorDescriptorV1",
    "CorrelationV1",
    "EventDataV1",
    "FeedbackItemDataV1",
    "FeedbackTransitionDataV1",
    "IncidentDataV1",
    "MetricDataV1",
    "RecordDedupeV1",
    "RecordDraftV1",
    "RecordEnvelopeV1",
    "RecordError",
    "RecordIdentityV1",
    "RunDataV1",
    "SourceDescriptorV1",
    "SpanDataV1",
    "TargetDescriptorV1",
    "VerificationSpecV1",
    "derive_content_hash",
    "derive_dedupe_key",
    "derive_record_id",
    "finalize_record",
    "verify_record_identity",
]
